# Generated by Django 5.1.15 on 2026-08-23 17:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_alter_invitation_role_alter_membership_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_label', models.CharField(blank=True, help_text='Kept as text so the entry survives the account being deleted.', max_length=255, verbose_name='who (recorded)')),
                ('category', models.CharField(choices=[('reporter_contact', 'Contact details of a reporter'), ('owner_data', 'Owner data'), ('internal_document', 'Internal document'), ('internal_notes', 'Internal notes'), ('data_export', 'Personal data export'), ('bulk_export', 'Bulk export')], max_length=32, verbose_name='category')),
                ('object_reference', models.CharField(blank=True, help_text='Reference of the record or report concerned.', max_length=255, verbose_name='object')),
                ('purpose', models.CharField(blank=True, max_length=255, verbose_name='purpose')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to=settings.AUTH_USER_MODEL, verbose_name='who')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='organizations.organization', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'access log entry',
                'verbose_name_plural': 'access log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category'], name='compliance__categor_831665_idx'), models.Index(fields=['created_at'], name='compliance__created_5ff3a8_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_label', models.CharField(blank=True, help_text='For consents without an account, e.g. a report reference.', max_length=255, verbose_name='subject')),
                ('purpose', models.CharField(choices=[('report_submission', 'Submitting a report'), ('feedback_contact', 'Being contacted about a report'), ('newsletter', 'Newsletter'), ('recognition', 'Being named as a contributor'), ('analytics', 'Usage analytics')], max_length=32, verbose_name='purpose')),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='granted at')),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True, verbose_name='withdrawn at')),
                ('source', models.CharField(blank=True, help_text='Where it was given: report form, API, newsletter, settings.', max_length=120, verbose_name='source')),
                ('policy_version', models.CharField(blank=True, help_text='Which version of the notice was shown at the time.', max_length=64, verbose_name='policy version')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'consent',
                'verbose_name_plural': 'consents',
                'ordering': ['-granted_at'],
                'indexes': [models.Index(fields=['purpose'], name='compliance__purpose_a71ea2_idx')],
            },
        ),
    ]
