# Generated by Django 5.1.15 on 2026-08-23 16:50

import apps.inspections.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_alter_invitation_role_alter_membership_role'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('desk_check', 'Preliminary check from the file'), ('on_site', 'On-site inspection'), ('follow_up', 'Follow-up inspection')], default='on_site', max_length=20, verbose_name='kind')),
                ('result', models.CharField(choices=[('confirmed', 'Confirmed'), ('not_confirmed', 'Not confirmed'), ('unclear', 'Unclear')], max_length=20, verbose_name='result')),
                ('inspected_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='inspected on')),
                ('inspector_role', models.CharField(blank=True, choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('member', 'Member'), ('building_authority', 'Building authority'), ('urban_planning', 'Urban planning'), ('property_management', 'Property management'), ('economic_development', 'Economic development'), ('regulatory_office', 'Regulatory office'), ('heritage_authority', 'Heritage authority'), ('external_agency', 'External public body'), ('verified_contributor', 'Verified contributor'), ('owner_representative', 'Property owner')], max_length=32, verbose_name='inspector role')),
                ('observed_vacancy_status', models.CharField(choices=[('unknown', 'Unknown'), ('suspected_vacant', 'Suspected vacant'), ('vacant', 'Vacant'), ('partially_vacant', 'Partially vacant'), ('in_use', 'In use'), ('under_renovation', 'Under renovation'), ('demolished', 'Demolished')], default='unknown', max_length=32, verbose_name='observed occupancy')),
                ('observed_condition', models.CharField(choices=[('good', 'Good condition'), ('minor_repair', 'Minor renovation needed'), ('major_repair', 'Significant renovation needed'), ('severely_damaged', 'Severely damaged'), ('dangerous', 'Acutely dangerous'), ('collapse_risk', 'Possible risk of collapse'), ('unknown', 'Not assessed')], default='unknown', max_length=32, verbose_name='observed condition')),
                ('observed_damage', models.JSONField(blank=True, default=list, verbose_name='observed damage')),
                ('findings', models.TextField(blank=True, help_text='What was established on site. Internal.', verbose_name='findings')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='applied to the record at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to=settings.AUTH_USER_MODEL, verbose_name='inspector')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='properties.property', verbose_name='property record')),
            ],
            options={
                'verbose_name': 'verification',
                'verbose_name_plural': 'verifications',
                'ordering': ['-inspected_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.inspections.models.inspection_photo_path, verbose_name='photo')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='caption')),
                ('is_public', models.BooleanField(default=False, verbose_name='published')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inspections.inspection')),
            ],
            options={
                'verbose_name': 'verification photo',
                'verbose_name_plural': 'verification photos',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['result'], name='inspections_result_052a9a_idx'),
        ),
    ]
