# Generated by Django 5.1.15 on 2026-08-23 16:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_alter_invitation_role_alter_membership_role'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('unknown', 'Unknown'), ('suspected_vacant', 'Suspected vacant'), ('vacant', 'Vacant'), ('partially_vacant', 'Partially vacant'), ('in_use', 'In use'), ('under_renovation', 'Under renovation'), ('demolished', 'Demolished')], max_length=32, verbose_name='status')),
                ('started_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='from')),
                ('ended_on', models.DateField(blank=True, null=True, verbose_name='until')),
                ('source', models.CharField(blank=True, help_text='How this was established: site visit, report, owner information.', max_length=255, verbose_name='source')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_periods', to='properties.property', verbose_name='property')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_vacancy_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'vacancy period',
                'verbose_name_plural': 'vacancy periods',
                'ordering': ['-started_on', '-created_at'],
                'indexes': [models.Index(fields=['property', 'ended_on'], name='vacancies_v_propert_ea0a87_idx'), models.Index(fields=['status'], name='vacancies_v_status_ef78e9_idx')],
            },
        ),
    ]
