# Generated by Django 5.1.15 on 2026-08-23 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_alter_invitation_role_alter_membership_role'),
        ('properties', '0001_initial'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('check_property', 'Check the object'), ('on_site_appointment', 'Carry out an on-site appointment'), ('verify_heritage', 'Verify the heritage status'), ('clarify_ownership', 'Clarify the ownership'), ('update_photo', 'Update the photograph'), ('check_funding_area', 'Check the funding area'), ('check_parcel', 'Check the parcel'), ('contact_owner', 'Contact the owner'), ('other', 'Other')], default='check_property', max_length=32, verbose_name='type')),
                ('title', models.CharField(blank=True, help_text='Leave empty to use the wording of the type.', max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='open', max_length=20, verbose_name='status')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16, verbose_name='priority')),
                ('due_on', models.DateField(blank=True, null=True, verbose_name='due on')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('completion_note', models.TextField(blank=True, verbose_name='completion note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='assigned to')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='properties.property', verbose_name='property record')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='reports.report', verbose_name='report')),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'tasks',
                'ordering': ['status', 'due_on', '-priority', '-created_at'],
                'indexes': [models.Index(fields=['status'], name='workflows_t_status_989c73_idx'), models.Index(fields=['due_on'], name='workflows_t_due_on_cd3862_idx')],
            },
        ),
    ]
