# Generated by Django 5.1.15 on 2026-08-23 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_alter_invitation_role_alter_membership_role'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingProgramme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('provider', models.CharField(blank=True, max_length=255, verbose_name='provider')),
                ('level', models.CharField(choices=[('municipal', 'Municipal'), ('district', 'District'), ('state', 'State'), ('federal', 'Federal'), ('european', 'European')], default='municipal', max_length=20, verbose_name='level')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('url', models.URLField(blank=True, verbose_name='information')),
                ('required_layer_slugs', models.JSONField(blank=True, default=list, help_text='Layer keys an object has to fall inside to be eligible.', verbose_name='required geodata layers')),
                ('starts_on', models.DateField(blank=True, null=True, verbose_name='starts on')),
                ('ends_on', models.DateField(blank=True, null=True, verbose_name='ends on')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'funding programme',
                'verbose_name_plural': 'funding programmes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyFunding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('possible', 'Possibly eligible'), ('checked', 'Eligibility checked'), ('prepared', 'Application prepared'), ('submitted', 'Application submitted'), ('granted', 'Granted'), ('rejected', 'Rejected'), ('not_eligible', 'Not eligible')], default='possible', max_length=20, verbose_name='status')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='amount')),
                ('reference', models.CharField(blank=True, max_length=120, verbose_name='file reference')),
                ('note', models.TextField(blank=True, verbose_name='internal note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='funding.fundingprogramme')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundings', to='properties.property', verbose_name='property record')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_fundings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'property funding',
                'verbose_name_plural': 'property fundings',
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('property', 'programme'), name='unique_funding_per_property_programme')],
            },
        ),
    ]
