# Generated by Django 5.1.15 on 2026-08-23 16:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_alter_invitation_role_alter_membership_role'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonumentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255, verbose_name='designation')),
                ('monument_id', models.CharField(blank=True, help_text='Number in the official list of monuments.', max_length=64, verbose_name='monument number')),
                ('scope', models.CharField(choices=[('single', 'Individual monument'), ('ensemble', 'Part of an ensemble'), ('area', 'Within a protected area'), ('ground', 'Archaeological monument'), ('garden', 'Historic garden')], default='single', max_length=20, verbose_name='scope')),
                ('authority', models.CharField(blank=True, help_text='Lower heritage authority or state office.', max_length=255, verbose_name='responsible authority')),
                ('listed_on', models.DateField(blank=True, null=True, verbose_name='listed on')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('source', models.CharField(blank=True, max_length=255, verbose_name='source')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monument_records', to='properties.property', verbose_name='property record')),
            ],
            options={
                'verbose_name': 'monument',
                'verbose_name_plural': 'monuments',
                'ordering': ['designation'],
            },
        ),
        migrations.CreateModel(
            name='HeritageCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('protected', 'Listed'), ('not_protected', 'Not listed'), ('unclear', 'Unclear')], max_length=20, verbose_name='result')),
                ('checked_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='checked on')),
                ('authority_reference', models.CharField(blank=True, help_text='File reference of the enquiry, so the answer is traceable.', max_length=255, verbose_name='authority reference')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heritage_checks', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heritage_checks', to='properties.property', verbose_name='property record')),
                ('monument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checks', to='heritage.monumentrecord', verbose_name='monument')),
            ],
            options={
                'verbose_name': 'heritage check',
                'verbose_name_plural': 'heritage checks',
                'ordering': ['-checked_on', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='monumentrecord',
            index=models.Index(fields=['monument_id'], name='heritage_mo_monumen_54a07a_idx'),
        ),
    ]
