# Generated by Django 5.1.15 on 2026-08-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('member', 'Member'), ('building_authority', 'Building authority'), ('urban_planning', 'Urban planning'), ('property_management', 'Property management'), ('economic_development', 'Economic development'), ('regulatory_office', 'Regulatory office'), ('heritage_authority', 'Heritage authority'), ('external_agency', 'External public body'), ('verified_contributor', 'Verified contributor'), ('owner_representative', 'Property owner')], default='member', max_length=20),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('member', 'Member'), ('building_authority', 'Building authority'), ('urban_planning', 'Urban planning'), ('property_management', 'Property management'), ('economic_development', 'Economic development'), ('regulatory_office', 'Regulatory office'), ('heritage_authority', 'Heritage authority'), ('external_agency', 'External public body'), ('verified_contributor', 'Verified contributor'), ('owner_representative', 'Property owner')], default='member', max_length=20),
        ),
    ]
