# Generated by Django 5.1.15 on 2026-08-23 17:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_alter_invitation_role_alter_membership_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeerInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('level', models.CharField(choices=[('municipality', 'Neighbouring municipality'), ('district', 'District'), ('state', 'State'), ('research', 'Research or statistics body')], default='district', max_length=20, verbose_name='level')),
                ('base_url', models.URLField(help_text="Root of the peer's API, e.g. https://example.de/api/v1/", verbose_name='base URL')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='contact')),
                ('outbound_key_hash', models.CharField(blank=True, editable=False, max_length=64, verbose_name='outbound key hash')),
                ('is_active', models.BooleanField(default=False, verbose_name='active')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'peer instance',
                'verbose_name_plural': 'peer instances',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('outbound', 'We send'), ('inbound', 'We receive')], max_length=10, verbose_name='direction')),
                ('category', models.CharField(choices=[('published_records', 'Published objects'), ('aggregate_statistics', 'Aggregated key figures'), ('anonymised_records', 'Objects without free text'), ('incoming_reports', 'Reports routed to this instance')], max_length=32, verbose_name='category')),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refused', 'Refused by the peer')], default='running', max_length=20, verbose_name='status')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('record_count', models.PositiveIntegerField(default=0, verbose_name='records')),
                ('message', models.TextField(blank=True, verbose_name='message')),
                ('peer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_runs', to='federation.peerinstance')),
            ],
            options={
                'verbose_name': 'synchronisation run',
                'verbose_name_plural': 'synchronisation runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ShareScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('published_records', 'Published objects'), ('aggregate_statistics', 'Aggregated key figures'), ('anonymised_records', 'Objects without free text'), ('incoming_reports', 'Reports routed to this instance')], max_length=32, verbose_name='category')),
                ('direction', models.CharField(choices=[('outbound', 'We send'), ('inbound', 'We receive')], default='outbound', max_length=10, verbose_name='direction')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='enabled')),
                ('decided_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='federation_decisions', to=settings.AUTH_USER_MODEL)),
                ('peer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_scopes', to='federation.peerinstance')),
            ],
            options={
                'verbose_name': 'share scope',
                'verbose_name_plural': 'share scopes',
                'ordering': ['peer', 'category'],
                'constraints': [models.UniqueConstraint(fields=('peer', 'category', 'direction'), name='unique_scope_per_peer_category_direction')],
            },
        ),
    ]
