# Generated by Django 5.1.15 on 2026-08-23 16:21

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_alter_invitation_role_alter_membership_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('municipality', 'Municipality'), ('district_authority', 'District authority'), ('state_authority', 'State authority')], default='municipality', max_length=32, verbose_name='kind')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('official_name', models.CharField(blank=True, help_text='Full legal name, if it differs from the everyday name.', max_length=255, verbose_name='official name')),
                ('municipality_key', models.CharField(blank=True, help_text='Official municipality key (AGS), digits only.', max_length=12, validators=[django.core.validators.RegexValidator('^\\d{5,12}$', 'Enter the official municipality key as digits only.')], verbose_name='municipality key')),
                ('state', models.CharField(choices=[('BW', 'Baden-Württemberg'), ('BY', 'Bavaria'), ('BE', 'Berlin'), ('BB', 'Brandenburg'), ('HB', 'Bremen'), ('HH', 'Hamburg'), ('HE', 'Hesse'), ('MV', 'Mecklenburg-Vorpommern'), ('NI', 'Lower Saxony'), ('NW', 'North Rhine-Westphalia'), ('RP', 'Rhineland-Palatinate'), ('SL', 'Saarland'), ('SN', 'Saxony'), ('ST', 'Saxony-Anhalt'), ('SH', 'Schleswig-Holstein'), ('TH', 'Thuringia')], max_length=2, verbose_name='federal state')),
                ('district_name', models.CharField(blank=True, help_text='The rural or urban district this municipality belongs to.', max_length=200, verbose_name='district')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='contact email')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='contact phone')),
                ('postal_address', models.TextField(blank=True, verbose_name='postal address')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('centre', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Where the map opens. Falls back to the instance default.', null=True, srid=4326, verbose_name='map centre')),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, help_text='Territory of this municipality, used to route reports to it.', null=True, srid=4326, verbose_name='boundary')),
                ('default_zoom', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='default zoom')),
                ('domain', models.CharField(blank=True, help_text='Host this instance answers on, used to pick the branding.', max_length=255, verbose_name='domain')),
                ('logo', models.ImageField(blank=True, upload_to='branding/', verbose_name='logo')),
                ('coat_of_arms', models.ImageField(blank=True, upload_to='branding/', verbose_name='coat of arms')),
                ('primary_colour', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a colour as a hex value, for example #1d4ed8.')], verbose_name='primary colour')),
                ('accent_colour', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a colour as a hex value, for example #1d4ed8.')], verbose_name='accent colour')),
                ('font_family', models.CharField(blank=True, help_text="CSS font stack, for example 'Inter', system-ui, sans-serif.", max_length=255, verbose_name='font family')),
                ('imprint', models.TextField(blank=True, verbose_name='imprint')),
                ('privacy_notice', models.TextField(blank=True, verbose_name='privacy notice')),
                ('terms', models.TextField(blank=True, verbose_name='terms of use')),
                ('public_intro', models.TextField(blank=True, help_text='Shown to citizens on the landing page of the reporting portal.', verbose_name='public introduction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='municipality', to='organizations.organization', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'municipality',
                'verbose_name_plural': 'municipalities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ModuleActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('public_map', 'Public map'), ('anonymous_reports', 'Anonymous reports'), ('citizen_verification', 'Verification by citizens'), ('heritage', 'Heritage protection data'), ('funding', 'Funding programmes'), ('owner_portal', 'Owner portal'), ('participation', 'Participation and reputation'), ('federation', 'Federation with other instances'), ('public_api', 'Public API')], max_length=64, verbose_name='module')),
                ('enabled', models.BooleanField(default=True, verbose_name='enabled')),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_activations', to='municipalities.municipality')),
            ],
            options={
                'verbose_name': 'module activation',
                'verbose_name_plural': 'module activations',
                'ordering': ['municipality', 'module'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('kind', models.CharField(choices=[('borough', 'Borough'), ('locality', 'Locality'), ('quarter', 'Quarter')], default='locality', max_length=20, verbose_name='kind')),
                ('code', models.CharField(blank=True, help_text='Official or internal key for this district.', max_length=32, verbose_name='code')),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='boundary')),
                ('centre', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='centre')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='municipalities.municipality')),
            ],
            options={
                'verbose_name': 'district',
                'verbose_name_plural': 'districts',
                'ordering': ['municipality', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='municipality',
            index=models.Index(fields=['domain'], name='municipalit_domain_175199_idx'),
        ),
        migrations.AddConstraint(
            model_name='moduleactivation',
            constraint=models.UniqueConstraint(fields=('municipality', 'module'), name='unique_module_per_municipality'),
        ),
        migrations.AddConstraint(
            model_name='district',
            constraint=models.UniqueConstraint(fields=('municipality', 'name'), name='unique_district_name_per_municipality'),
        ),
    ]
