# Generated by Django 5.1.15 on 2026-08-23 16:59

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_alter_invitation_role_alter_membership_role'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', models.SlugField(help_text='Stable key, so a repeated import replaces the same layer.', max_length=255, verbose_name='key')),
                ('category', models.CharField(choices=[('heritage', 'Heritage protection'), ('redevelopment', 'Redevelopment area'), ('funding', 'Funding area'), ('urban_restructuring', 'Urban restructuring area'), ('development', 'Development area'), ('quarter', 'Quarter of particular significance'), ('land_value', 'Standard land value zone'), ('other', 'Other')], default='other', max_length=32, verbose_name='category')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('source', models.CharField(blank=True, help_text='Where the data came from, e.g. the state geodata portal.', max_length=255, verbose_name='source')),
                ('source_url', models.URLField(blank=True, verbose_name='source URL')),
                ('licence', models.CharField(blank=True, max_length=255, verbose_name='licence')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive layers are kept but ignored when deriving context.', verbose_name='active')),
                ('is_public', models.BooleanField(default=False, help_text='Whether this layer may be shown on the public map.', verbose_name='public')),
                ('imported_at', models.DateTimeField(blank=True, null=True, verbose_name='imported at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'geodata layer',
                'verbose_name_plural': 'geodata layers',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GeoFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('external_id', models.CharField(blank=True, help_text='Identifier in the source system, for repeatable imports.', max_length=255, verbose_name='external id')),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326, verbose_name='geometry')),
                ('attributes', models.JSONField(blank=True, default=dict, verbose_name='attributes')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='geodata.geolayer')),
            ],
            options={
                'verbose_name': 'geodata feature',
                'verbose_name_plural': 'geodata features',
                'ordering': ['layer', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SpatialContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_at', models.DateTimeField(auto_now=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spatial_contexts', to='geodata.geofeature')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spatial_contexts', to='properties.property', verbose_name='property record')),
            ],
            options={
                'verbose_name': 'spatial context',
                'verbose_name_plural': 'spatial contexts',
                'ordering': ['feature__layer__category'],
            },
        ),
        migrations.AddConstraint(
            model_name='geolayer',
            constraint=models.UniqueConstraint(fields=('organization', 'slug'), name='unique_layer_slug_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='geofeature',
            index=models.Index(fields=['external_id'], name='geodata_geo_externa_3374c8_idx'),
        ),
        migrations.AddConstraint(
            model_name='spatialcontext',
            constraint=models.UniqueConstraint(fields=('property', 'feature'), name='unique_context_per_property_feature'),
        ),
    ]
