# Generated by Django 5.1.15 on 2026-08-23 16:32

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_alter_invitation_role_alter_membership_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastral_district', models.CharField(blank=True, help_text='Gemarkung, as used by the cadastre.', max_length=120, verbose_name='cadastral district')),
                ('field_number', models.CharField(blank=True, help_text='Flur.', max_length=32, verbose_name='field number')),
                ('parcel_number', models.CharField(help_text='Flurstücksnummer.', max_length=64, verbose_name='parcel number')),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='geometry')),
                ('area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='area in m²')),
                ('source', models.CharField(choices=[('manual', 'Recorded manually'), ('cadastre', 'Official cadastre'), ('import', 'Geodata import')], default='manual', max_length=20, verbose_name='source')),
                ('source_reference', models.CharField(blank=True, help_text='Identifier in the originating system, for repeatable imports.', max_length=255, verbose_name='source reference')),
                ('imported_at', models.DateTimeField(blank=True, null=True, verbose_name='imported at')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'parcel',
                'verbose_name_plural': 'parcels',
                'ordering': ['cadastral_district', 'field_number', 'parcel_number'],
                'indexes': [models.Index(fields=['parcel_number'], name='parcels_par_parcel__2f6f5d_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'cadastral_district', 'field_number', 'parcel_number'), name='unique_parcel_per_tenant')],
            },
        ),
    ]
