# Generated by Django 5.1.15 on 2026-08-23 16:32

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('municipalities', '0001_initial'),
        ('organizations', '0002_alter_invitation_role_alter_membership_role'),
        ('parcels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProperty',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('reference', models.CharField(blank=True, help_text='Register number, assigned automatically.', max_length=32, verbose_name='reference')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='street')),
                ('house_number', models.CharField(blank=True, max_length=32, verbose_name='house number')),
                ('postal_code', models.CharField(blank=True, max_length=16, verbose_name='postal code')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='city')),
                ('address_note', models.CharField(blank=True, help_text='For objects without a usable address, e.g. “behind no. 14”.', max_length=255, verbose_name='address note')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Where the object sits on the map.', null=True, srid=4326, verbose_name='location')),
                ('property_type', models.CharField(choices=[('residential', 'Residential building'), ('mixed_use', 'Mixed-use building'), ('commercial', 'Commercial building'), ('retail', 'Retail premises'), ('office', 'Office building'), ('industrial', 'Industrial or workshop building'), ('agricultural', 'Agricultural building'), ('public', 'Public building'), ('religious', 'Religious building'), ('outbuilding', 'Outbuilding or garage'), ('brownfield', 'Brownfield site'), ('building_gap', 'Building gap'), ('undeveloped', 'Undeveloped plot'), ('other', 'Other')], default='residential', max_length=32, verbose_name='property type')),
                ('last_known_use', models.CharField(choices=[('housing', 'Housing'), ('retail', 'Retail'), ('hospitality', 'Hospitality'), ('office', 'Office'), ('craft', 'Craft or workshop'), ('storage', 'Storage'), ('production', 'Production'), ('public', 'Public use'), ('cultural', 'Cultural use'), ('agriculture', 'Agriculture'), ('never_used', 'Never used'), ('unknown', 'Unknown')], default='unknown', max_length=32, verbose_name='last known use')),
                ('status', models.CharField(choices=[('new', 'New'), ('pre_check', 'Preliminary check'), ('on_site_check', 'On-site check'), ('confirmed', 'Confirmed'), ('not_confirmed', 'Not confirmed'), ('unclear', 'Unclear'), ('research', 'Further research'), ('measures', 'Measures under way'), ('monitoring', 'Monitoring'), ('archived', 'Archived')], default='new', max_length=32, verbose_name='record status')),
                ('vacancy_status', models.CharField(choices=[('unknown', 'Unknown'), ('suspected_vacant', 'Suspected vacant'), ('vacant', 'Vacant'), ('partially_vacant', 'Partially vacant'), ('in_use', 'In use'), ('under_renovation', 'Under renovation'), ('demolished', 'Demolished')], default='unknown', max_length=32, verbose_name='vacancy status')),
                ('condition', models.CharField(choices=[('good', 'Good condition'), ('minor_repair', 'Minor renovation needed'), ('major_repair', 'Significant renovation needed'), ('severely_damaged', 'Severely damaged'), ('dangerous', 'Acutely dangerous'), ('collapse_risk', 'Possible risk of collapse'), ('unknown', 'Not assessed')], default='unknown', max_length=32, verbose_name='condition')),
                ('condition_source', models.CharField(choices=[('citizen_observation', 'Citizen observation'), ('staff_assessment', 'Assessment by the administration'), ('expert_report', 'Expert report'), ('unknown', 'Unknown')], default='unknown', help_text='The register does not replace an expert opinion.', max_length=32, verbose_name='condition assessed by')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16, verbose_name='priority')),
                ('recorded_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='recorded on')),
                ('last_checked_on', models.DateField(blank=True, null=True, verbose_name='last checked on')),
                ('public_description', models.TextField(blank=True, help_text='Visible to everyone wherever this object is published.', verbose_name='public description')),
                ('internal_description', models.TextField(blank=True, help_text='Never leaves the administration.', verbose_name='internal description')),
                ('sources', models.TextField(blank=True, help_text='Where the information came from: reports, site visits, files.', verbose_name='sources')),
                ('is_public', models.BooleanField(default=False, help_text='Whether this object appears on the public map and in the public API.', verbose_name='published')),
                ('plot_area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='plot area in m²')),
                ('usable_area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='usable area in m²')),
                ('living_area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='living area in m²')),
                ('year_built', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='year built')),
                ('units_total', models.PositiveIntegerField(blank=True, null=True, verbose_name='units in total')),
                ('units_vacant', models.PositiveIntegerField(blank=True, null=True, verbose_name='vacant units')),
                ('is_heritage_protected', models.BooleanField(default=False, verbose_name='heritage protected')),
                ('in_redevelopment_area', models.BooleanField(default=False, verbose_name='in a redevelopment area')),
                ('in_funding_area', models.BooleanField(default=False, verbose_name='in a funding area')),
                ('in_development_area', models.BooleanField(default=False, verbose_name='in a development area')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='municipalities.district', verbose_name='district')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'historical property',
                'verbose_name_plural': 'historical properties',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, help_text='Register number, assigned automatically.', max_length=32, verbose_name='reference')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='street')),
                ('house_number', models.CharField(blank=True, max_length=32, verbose_name='house number')),
                ('postal_code', models.CharField(blank=True, max_length=16, verbose_name='postal code')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='city')),
                ('address_note', models.CharField(blank=True, help_text='For objects without a usable address, e.g. “behind no. 14”.', max_length=255, verbose_name='address note')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Where the object sits on the map.', null=True, srid=4326, verbose_name='location')),
                ('property_type', models.CharField(choices=[('residential', 'Residential building'), ('mixed_use', 'Mixed-use building'), ('commercial', 'Commercial building'), ('retail', 'Retail premises'), ('office', 'Office building'), ('industrial', 'Industrial or workshop building'), ('agricultural', 'Agricultural building'), ('public', 'Public building'), ('religious', 'Religious building'), ('outbuilding', 'Outbuilding or garage'), ('brownfield', 'Brownfield site'), ('building_gap', 'Building gap'), ('undeveloped', 'Undeveloped plot'), ('other', 'Other')], default='residential', max_length=32, verbose_name='property type')),
                ('last_known_use', models.CharField(choices=[('housing', 'Housing'), ('retail', 'Retail'), ('hospitality', 'Hospitality'), ('office', 'Office'), ('craft', 'Craft or workshop'), ('storage', 'Storage'), ('production', 'Production'), ('public', 'Public use'), ('cultural', 'Cultural use'), ('agriculture', 'Agriculture'), ('never_used', 'Never used'), ('unknown', 'Unknown')], default='unknown', max_length=32, verbose_name='last known use')),
                ('status', models.CharField(choices=[('new', 'New'), ('pre_check', 'Preliminary check'), ('on_site_check', 'On-site check'), ('confirmed', 'Confirmed'), ('not_confirmed', 'Not confirmed'), ('unclear', 'Unclear'), ('research', 'Further research'), ('measures', 'Measures under way'), ('monitoring', 'Monitoring'), ('archived', 'Archived')], default='new', max_length=32, verbose_name='record status')),
                ('vacancy_status', models.CharField(choices=[('unknown', 'Unknown'), ('suspected_vacant', 'Suspected vacant'), ('vacant', 'Vacant'), ('partially_vacant', 'Partially vacant'), ('in_use', 'In use'), ('under_renovation', 'Under renovation'), ('demolished', 'Demolished')], default='unknown', max_length=32, verbose_name='vacancy status')),
                ('condition', models.CharField(choices=[('good', 'Good condition'), ('minor_repair', 'Minor renovation needed'), ('major_repair', 'Significant renovation needed'), ('severely_damaged', 'Severely damaged'), ('dangerous', 'Acutely dangerous'), ('collapse_risk', 'Possible risk of collapse'), ('unknown', 'Not assessed')], default='unknown', max_length=32, verbose_name='condition')),
                ('condition_source', models.CharField(choices=[('citizen_observation', 'Citizen observation'), ('staff_assessment', 'Assessment by the administration'), ('expert_report', 'Expert report'), ('unknown', 'Unknown')], default='unknown', help_text='The register does not replace an expert opinion.', max_length=32, verbose_name='condition assessed by')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16, verbose_name='priority')),
                ('recorded_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='recorded on')),
                ('last_checked_on', models.DateField(blank=True, null=True, verbose_name='last checked on')),
                ('public_description', models.TextField(blank=True, help_text='Visible to everyone wherever this object is published.', verbose_name='public description')),
                ('internal_description', models.TextField(blank=True, help_text='Never leaves the administration.', verbose_name='internal description')),
                ('sources', models.TextField(blank=True, help_text='Where the information came from: reports, site visits, files.', verbose_name='sources')),
                ('is_public', models.BooleanField(default=False, help_text='Whether this object appears on the public map and in the public API.', verbose_name='published')),
                ('plot_area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='plot area in m²')),
                ('usable_area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='usable area in m²')),
                ('living_area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='living area in m²')),
                ('year_built', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='year built')),
                ('units_total', models.PositiveIntegerField(blank=True, null=True, verbose_name='units in total')),
                ('units_vacant', models.PositiveIntegerField(blank=True, null=True, verbose_name='vacant units')),
                ('is_heritage_protected', models.BooleanField(default=False, verbose_name='heritage protected')),
                ('in_redevelopment_area', models.BooleanField(default=False, verbose_name='in a redevelopment area')),
                ('in_funding_area', models.BooleanField(default=False, verbose_name='in a funding area')),
                ('in_development_area', models.BooleanField(default=False, verbose_name='in a development area')),
                ('context_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='spatial context updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_properties', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='municipalities.district', verbose_name='district')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('parcels', models.ManyToManyField(blank=True, help_text='A building can sit on more than one parcel.', related_name='properties', to='parcels.parcel', verbose_name='parcels')),
            ],
            options={
                'verbose_name': 'property',
                'verbose_name_plural': 'properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyDamage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_type', models.CharField(choices=[('roof', 'Roof'), ('facade', 'Facade'), ('windows', 'Windows or doors'), ('moisture', 'Moisture or mould'), ('vegetation', 'Vegetation growth'), ('falling_parts', 'Falling building parts'), ('structure', 'Load-bearing structure'), ('utilities', 'Building services'), ('vandalism', 'Vandalism'), ('waste', 'Waste or accumulation'), ('other', 'Other')], max_length=32, verbose_name='damage')),
                ('severity', models.CharField(choices=[('present', 'Present'), ('severe', 'Severe'), ('hazardous', 'Hazardous')], default='present', max_length=16, verbose_name='severity')),
                ('source', models.CharField(choices=[('citizen_observation', 'Citizen observation'), ('staff_assessment', 'Assessment by the administration'), ('expert_report', 'Expert report'), ('unknown', 'Unknown')], default='unknown', max_length=32, verbose_name='noted by')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='note')),
                ('noted_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damages', to='properties.property')),
            ],
            options={
                'verbose_name': 'damage',
                'verbose_name_plural': 'damages',
                'ordering': ['damage_type'],
            },
        ),
        migrations.CreateModel(
            name='StatusTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('new', 'New'), ('pre_check', 'Preliminary check'), ('on_site_check', 'On-site check'), ('confirmed', 'Confirmed'), ('not_confirmed', 'Not confirmed'), ('unclear', 'Unclear'), ('research', 'Further research'), ('measures', 'Measures under way'), ('monitoring', 'Monitoring'), ('archived', 'Archived')], max_length=32, verbose_name='from')),
                ('to_status', models.CharField(choices=[('new', 'New'), ('pre_check', 'Preliminary check'), ('on_site_check', 'On-site check'), ('confirmed', 'Confirmed'), ('not_confirmed', 'Not confirmed'), ('unclear', 'Unclear'), ('research', 'Further research'), ('measures', 'Measures under way'), ('monitoring', 'Monitoring'), ('archived', 'Archived')], max_length=32, verbose_name='to')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='reason')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_transitions', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_transitions', to='properties.property')),
            ],
            options={
                'verbose_name': 'status change',
                'verbose_name_plural': 'status changes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status'], name='properties__status_6427a0_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['vacancy_status'], name='properties__vacancy_6d0b2f_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['condition'], name='properties__conditi_fb124e_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_public'], name='properties__is_publ_373e00_idx'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.UniqueConstraint(fields=('organization', 'reference'), name='unique_property_reference_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='propertydamage',
            constraint=models.UniqueConstraint(fields=('property', 'damage_type'), name='unique_damage_type_per_property'),
        ),
    ]
