# Generated by Django 5.1.15 on 2026-08-23 17:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_alter_invitation_role_alter_membership_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64, unique=True, verbose_name='key')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('icon', models.CharField(blank=True, help_text='A single character or emoji.', max_length=16, verbose_name='icon')),
                ('required_points', models.PositiveIntegerField(default=0, verbose_name='points required')),
                ('required_confirmed_reports', models.PositiveIntegerField(default=0, verbose_name='confirmed reports required')),
                ('required_inspections', models.PositiveIntegerField(default=0, verbose_name='verifications required')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'badge',
                'verbose_name_plural': 'badges',
                'ordering': ['required_points', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContributorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='points')),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'Newcomer'), (1, 'Contributor'), (2, 'Regular'), (3, 'Trusted'), (4, 'Expert')], default=0, verbose_name='level')),
                ('reports_accepted', models.PositiveIntegerField(default=0, verbose_name='reports accepted')),
                ('reports_confirmed', models.PositiveIntegerField(default=0, verbose_name='reports confirmed')),
                ('inspections_completed', models.PositiveIntegerField(default=0, verbose_name='verifications')),
                ('tasks_completed', models.PositiveIntegerField(default=0, verbose_name='tasks completed')),
                ('display_name', models.CharField(blank=True, help_text='Optional name for acknowledgements. Left empty means anonymous.', max_length=120, verbose_name='display name')),
                ('wants_recognition', models.BooleanField(default=False, help_text='Nobody is named publicly without having agreed to it.', verbose_name='agrees to be named')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributor_profiles', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'contributor profile',
                'verbose_name_plural': 'contributor profiles',
                'ordering': ['-points'],
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='participation.badge')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='participation.contributorprofile')),
            ],
            options={
                'verbose_name': 'award',
                'verbose_name_plural': 'awards',
                'ordering': ['-awarded_at'],
            },
        ),
        migrations.CreateModel(
            name='PointEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('report_confirmed', 'Report led to a confirmed object'), ('report_accepted', 'Report accepted into the register'), ('inspection_completed', 'Verification carried out'), ('task_completed', 'Task completed'), ('manual', 'Awarded by the administration')], max_length=32, verbose_name='reason')),
                ('points', models.IntegerField(verbose_name='points')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('awarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarded_points', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_entries', to='participation.contributorprofile')),
            ],
            options={
                'verbose_name': 'point entry',
                'verbose_name_plural': 'point entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='contributorprofile',
            constraint=models.UniqueConstraint(fields=('organization', 'user'), name='unique_contributor_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='award',
            constraint=models.UniqueConstraint(fields=('profile', 'badge'), name='unique_award_per_badge'),
        ),
    ]
