# Generated by Django 5.1.15 on 2026-08-23 17:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_alter_invitation_role_alter_membership_role'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('private', 'Private individual'), ('company', 'Company'), ('community_of_heirs', 'Community of heirs'), ('public_body', 'Public body'), ('church', 'Church or foundation'), ('association', 'Association'), ('unknown', 'Unknown')], default='unknown', max_length=32, verbose_name='kind')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('contact_state', models.CharField(choices=[('unknown', 'Owner unknown'), ('identified', 'Owner identified, no contact details'), ('contactable', 'Contact details available'), ('contacted', 'Contact attempted'), ('in_dialogue', 'In dialogue'), ('unreachable', 'Not reachable')], default='unknown', max_length=20, verbose_name='contact state')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='phone')),
                ('postal_address', models.TextField(blank=True, verbose_name='postal address')),
                ('representative', models.CharField(blank=True, help_text='Administrator, agent or spokesperson of a community of heirs.', max_length=255, verbose_name='representative')),
                ('note', models.TextField(blank=True, verbose_name='internal note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'owner',
                'verbose_name_plural': 'owners',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OwnerInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('sell', 'Willing to sell'), ('let', 'Willing to let'), ('renovate', 'Intends to renovate'), ('support_needed', 'Needs support'), ('develop_together', 'Open to joint development'), ('no_interest', 'No interest at present')], max_length=32, verbose_name='interest')),
                ('stated_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='stated on')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interests', to='owners.owner')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_interests', to='properties.property', verbose_name='property record')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_owner_interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'owner interest',
                'verbose_name_plural': 'owner interests',
                'ordering': ['-stated_on'],
            },
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', models.CharField(blank=True, help_text='Where ownership is divided, e.g. among heirs.', max_length=64, verbose_name='share')),
                ('source', models.CharField(blank=True, help_text='How this was established. Never a land registry extract in public data.', max_length=255, verbose_name='source')),
                ('recorded_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='recorded on')),
                ('note', models.TextField(blank=True, verbose_name='internal note')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='owners.owner')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='properties.property', verbose_name='property record')),
            ],
            options={
                'verbose_name': 'ownership',
                'verbose_name_plural': 'ownerships',
                'ordering': ['-recorded_on'],
                'constraints': [models.UniqueConstraint(fields=('property', 'owner'), name='unique_ownership_per_property_owner')],
            },
        ),
        migrations.CreateModel(
            name='OwnershipClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Awaiting review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20, verbose_name='status')),
                ('evidence_note', models.TextField(blank=True, help_text='What the claimant offered as proof. Never stored as a document here.', verbose_name='evidence')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, verbose_name='review note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_claims', to=settings.AUTH_USER_MODEL, verbose_name='claimant')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('owner', models.ForeignKey(blank=True, help_text='Set once the claim has been matched to a known owner.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='owners.owner')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_claims', to='properties.property', verbose_name='property record')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_ownership_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ownership claim',
                'verbose_name_plural': 'ownership claims',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'verified'])), fields=('property', 'claimant'), name='unique_open_claim_per_property_claimant')],
            },
        ),
    ]
