# Generated by Django 5.1.15 on 2026-08-23 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_alter_invitation_role_alter_membership_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, help_text='What this client is for. Useful when reviewing access later.', verbose_name='purpose')),
                ('contact_email', models.EmailField(blank=True, help_text='Who to reach if the access has to be withdrawn.', max_length=254, verbose_name='contact')),
                ('key_prefix', models.CharField(editable=False, max_length=16, verbose_name='key prefix')),
                ('key_hash', models.CharField(editable=False, max_length=64, verbose_name='key hash')),
                ('scopes', models.JSONField(default=list, verbose_name='scopes')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Leave empty for access without an end date.', null=True, verbose_name='expires at')),
                ('throttle_rate', models.CharField(default='1000/hour', help_text='Requests per period for this client, e.g. 1000/hour.', max_length=32, verbose_name='rate limit')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='last used')),
                ('request_count', models.PositiveBigIntegerField(default=0, verbose_name='requests')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='revoked at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_clients', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'API client',
                'verbose_name_plural': 'API clients',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['key_prefix'], name='integration_key_pre_65a23a_idx')],
            },
        ),
    ]
