# Generated by Django 5.1.15 on 2026-08-23 17:03

import apps.documents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_alter_invitation_role_alter_membership_role'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('photo', 'Photograph'), ('site_plan', 'Site plan'), ('expert_report', 'Expert report'), ('correspondence', 'Correspondence'), ('permit', 'Permit or notice'), ('land_registry', 'Land registry extract'), ('other', 'Other')], default='photo', max_length=32, verbose_name='kind')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('file', models.FileField(upload_to=apps.documents.models.document_upload_path, verbose_name='file')),
                ('visibility', models.CharField(choices=[('internal', 'Internal'), ('public', 'Public')], default='internal', help_text='Documents are internal unless released deliberately.', max_length=16, verbose_name='visibility')),
                ('recorded_on', models.DateField(blank=True, null=True, verbose_name='document date')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='properties.property', verbose_name='property record')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['kind'], name='documents_p_kind_0f2760_idx'), models.Index(fields=['visibility'], name='documents_p_visibil_51d7cb_idx')],
            },
        ),
    ]
