# Generated by Django 5.1.15 on 2026-08-23 16:43

import apps.reports.models
import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('municipalities', '0001_initial'),
        ('organizations', '0002_alter_invitation_role_alter_membership_role'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=32, verbose_name='reference')),
                ('category', models.CharField(choices=[('suspected_vacancy', 'Suspected vacancy'), ('building_damage', 'Visible building damage'), ('hazard', 'Hazard'), ('neglect', 'Neglect or accumulation of waste'), ('use_information', 'Information about use or condition'), ('other', 'Other')], default='suspected_vacancy', max_length=32, verbose_name='category')),
                ('description', models.TextField(blank=True, help_text='What did you notice? Anything you know about the building helps.', verbose_name='description')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='street')),
                ('house_number', models.CharField(blank=True, max_length=32, verbose_name='house number')),
                ('postal_code', models.CharField(blank=True, max_length=16, verbose_name='postal code')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='city')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='The marker the reporter placed on the map.', null=True, srid=4326, verbose_name='location')),
                ('damage_types', models.JSONField(blank=True, default=list, help_text='Damage the reporter marked. An observation, not an assessment.', verbose_name='observed damage')),
                ('contact_name', models.CharField(blank=True, max_length=200, verbose_name='name')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='phone')),
                ('wants_feedback', models.BooleanField(default=False, help_text='Only possible if contact details were provided.', verbose_name='would like to hear back')),
                ('accepted_privacy_policy', models.BooleanField(default=False, verbose_name='privacy policy accepted')),
                ('accepted_terms', models.BooleanField(default=False, verbose_name='terms accepted')),
                ('consent_given_at', models.DateTimeField(blank=True, null=True, verbose_name='consent given at')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('in_moderation', 'In moderation'), ('accepted', 'Accepted'), ('duplicate', 'Duplicate'), ('rejected', 'Rejected'), ('spam', 'Spam')], default='submitted', max_length=32, verbose_name='status')),
                ('moderation_note', models.TextField(blank=True, verbose_name='moderation note')),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_from_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='submitted from')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='municipalities.district')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_reports', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='properties.property', verbose_name='property record')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='submitted by')),
            ],
            options={
                'verbose_name': 'report',
                'verbose_name_plural': 'reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.reports.models.report_photo_path, verbose_name='photo')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='caption')),
                ('is_public', models.BooleanField(default=False, help_text='Photographs stay internal until they are released explicitly.', verbose_name='published')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='reports.report')),
            ],
            options={
                'verbose_name': 'report photo',
                'verbose_name_plural': 'report photos',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status'], name='reports_rep_status_c732ef_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['category'], name='reports_rep_categor_b7680f_idx'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('organization', 'reference'), name='unique_report_reference_per_tenant'),
        ),
    ]
