# Generated by Django 5.1.15 on 2026-08-23 17:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_alter_invitation_role_alter_membership_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyFigureSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='taken on')),
                ('figures', models.JSONField(default=dict, verbose_name='figures')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'key figure snapshot',
                'verbose_name_plural': 'key figure snapshots',
                'ordering': ['-taken_on'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'taken_on'), name='unique_snapshot_per_day')],
            },
        ),
    ]
